import { useEffect, useRef, useState } from 'react';
import { useAccount } from './AccountContext';
import { accountConfig, accountSession, googleLogin, loginChallenge } from './accounts-api';
import { loadGoogle } from './google-signin';
import { googleMapsLink } from '../../shared/routes';
import { API_BASE_URL } from './config';
import { useOnline } from './useOnline';
export default function Account() {
  const online = useOnline();
  const account = useAccount(); const [clientId, setClientId] = useState(''); const [configured, setConfigured] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('Checking sign-in configuration…');
  const [configAttempt, setConfigAttempt] = useState(0); const [checkingConfig, setCheckingConfig] = useState(true);
  const backButton = useRef<HTMLButtonElement>(null); const button = useRef<HTMLDivElement>(null); const controller = useRef<AbortController | null>(null); const run = useRef(0); const locked = useRef(false);
  const sameOrigin = new URL(API_BASE_URL, location.href).origin === location.origin;
  useEffect(() => { backButton.current?.focus(); const abort = new AbortController(); controller.current = abort; const generation = ++run.current;
    accountConfig(abort.signal).then(data => { if (!abort.signal.aborted) { setClientId(data.clientId); setConfigured(true); setMessage(data.clientId ? 'Sign in is optional. Your next detour needs no account.' : 'Google sign-in is not configured yet. Browsing still works.'); } }).catch(error => { if (!abort.signal.aborted) setMessage((error as Error).message); }).finally(() => { if (!abort.signal.aborted) setCheckingConfig(false); });
    return () => { abort.abort(); if (run.current === generation) ++run.current; };
  }, [configAttempt]);
  async function prepare() {
    if (locked.current) return; locked.current = true; setBusy(true); setMessage('Preparing Google sign-in…'); const generation = run.current; const signal = controller.current?.signal;
    try { const [google, challenge] = await Promise.all([loadGoogle(), loginChallenge(signal)]); if (signal?.aborted || generation !== run.current || !button.current) return;
      google.initialize({ client_id: clientId, nonce: challenge.nonce, auto_select: false, callback: data => { if (signal?.aborted || generation !== run.current || locked.current) return; locked.current = true; setBusy(true); setMessage('Verifying your sign-in…'); button.current?.replaceChildren();
        googleLogin(data.credential, signal).then(async () => { if (signal?.aborted || generation !== run.current) return; await account.refresh(); if (!signal?.aborted && generation === run.current) { const session = await accountSession(signal); setMessage(session.user ? 'Signed in. Your favorite spots are ready.' : 'The browser did not retain the secure session. Use the same-origin HTTPS preview and retry.'); } }).catch(error => { if (!signal?.aborted && generation === run.current) setMessage((error as Error).message); }).finally(() => { locked.current = false; if (!signal?.aborted && generation === run.current) setBusy(false); });
      } }); button.current.replaceChildren(); google.renderButton(button.current, { theme: 'outline', size: 'large', width: Math.min(280, button.current.clientWidth), text: 'signin_with' }); setMessage('Use the Google button below. It expires after five minutes; prepare again if needed.');
    } catch (error) { if (!signal?.aborted && generation === run.current) setMessage((error as Error).message); } finally { locked.current = false; if (!signal?.aborted && generation === run.current) setBusy(false); }
  }
  return <section className="special-days" aria-label="Account and favorites"><header className="explore-header"><button ref={backButton} onClick={() => account.setOpen(false)}>← Back</button><strong>Your little collection</strong></header><div className="calendar-content"><h1>Good spots. Saved.</h1><p>Browsing is free and needs no login. Google sign-in syncs up to 200 favorite places to your account.</p>
    {account.user ? <><p>Signed in as <strong>{account.user.name}</strong></p><button disabled={!online || busy || account.busy || account.loading} onClick={() => void account.signOut()}>Sign out</button></> : <><p>Preparing sign-in loads Google’s script and opens its sign-in flow. We store your Google account identifier and display name, not your email or Google token. The session lasts up to seven days. No location is added to your profile.</p><button disabled={!online || !configured || !clientId || !sameOrigin || busy || account.loading} onClick={() => void prepare()}>{busy ? 'Preparing…' : 'Prepare Google sign-in'}</button><div ref={button} className="google-signin"/>{!sameOrigin && <p role="alert">Accounts require the same-origin /api proxy. Update the app API configuration before signing in.</p>}<p role="status">{message}</p>{!configured && !checkingConfig && <button onClick={() => { setCheckingConfig(true); setMessage('Checking sign-in configuration…'); setConfigAttempt(value => value + 1); }}>Retry sign-in configuration</button>}{configured && !clientId && <p>The operator needs a public Google OAuth Web client ID, not an API key. Setup steps are in the project README.</p>}</>}
    <button disabled={!online || account.loading || account.busy || busy} onClick={() => void account.refresh()}>Refresh account &amp; favorites</button><p role="status">{account.message}</p><h2>Favorite spots</h2><p>Details are snapshots from when you saved them. Recheck current hours and venue details before visiting. Saved venue coordinates may be unknown.</p>{account.loading ? <p role="status">Loading your collection…</p> : !account.user && !account.cached ? <p>Sign in to save and reopen favorites. Explore and Safety remain available.</p> : !account.saved.length ? <p>No favorites yet. Open a spot or venue and choose Save this spot.</p> : <ul className="calendar-cards">{account.saved.map(({ place, savedAt }) => <li key={place.id}><span className="eyebrow">{place.category}</span><h3>{place.name}</h3><p>{place.address}</p><p>Hours: {place.hours}</p><p>Saved {new Date(savedAt).toLocaleDateString('en-IN')}</p><div className="booking-links">{place.sourceUrl && <a href={place.sourceUrl} target="_blank" rel="noreferrer">Check current source ↗</a>}{place.lat !== undefined && <a href={googleMapsLink({ lat: place.lat, lon: place.lon! }, 'drive')} target="_blank" rel="noreferrer">Directions ↗</a>}<button disabled={!online || account.cached || !account.user || account.busy || busy} onClick={() => void account.toggle(place)}>Remove {place.name}</button></div></li>)}</ul>}
  </div></section>;
}

