import { createContext, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import type { AccountUser, FavoritePlace, FavoriteRecord } from '../../shared/accounts';
import * as api from './accounts-api';
import { clearCollection, readCollection, saveCollection } from './offline';
interface AccountState { user: AccountUser | null; saved: FavoriteRecord[]; cached: boolean; loading: boolean; busy: boolean; message: string; open: boolean; setOpen: (open: boolean) => void; refresh: () => Promise<void>; toggle: (place: FavoritePlace) => Promise<void>; signOut: () => Promise<void> }
const Context = createContext<AccountState | null>(null);
export function useAccount() { const value = useContext(Context); if (!value) throw new Error('Account provider missing.'); return value; }
export function AccountProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AccountUser | null>(null); const [saved, setSaved] = useState<FavoriteRecord[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [open, updateOpen] = useState(false);
  const previousFocus = useRef<HTMLElement | null>(null);
  function setOpen(value: boolean) { if (value) previousFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; updateOpen(value); if (!value) requestAnimationFrame(() => { if (mounted.current) previousFocus.current?.focus({ preventScroll: true }); }); }
  const generation = useRef(0); const mounted = useRef(true); const lock = useRef(false);
  const [cached, setCached] = useState(false);
  useEffect(() => { mounted.current = true; const controller = new AbortController(); const run = ++generation.current;
    const stored = readCollection(); let owner = stored?.owner;
    (navigator.onLine ? api.accountSession(controller.signal) : Promise.reject(new Error('Offline.'))).then(async data => { if (controller.signal.aborted || run !== generation.current) return; setUser(data.user); owner = data.user?.id; if (!data.user || stored?.owner !== data.user.id) clearCollection(); if (data.user) { const rows = await api.favorites(controller.signal); if (!controller.signal.aborted && run === generation.current) { setSaved(rows); if (!saveCollection(data.user.id, rows)) setMessage('Favorites loaded, but offline storage is unavailable.'); } } }).catch(error => { if (!controller.signal.aborted && run === generation.current) { const snapshot = readCollection(); if (snapshot && snapshot.owner === owner) { setSaved(snapshot.rows); setCached(true); setMessage('Offline collection: sign-in is unverified. Changes need a connection.'); } else setMessage((error as Error).message); } }).finally(() => { if (!controller.signal.aborted && run === generation.current) setLoading(false); });
    return () => { mounted.current = false; controller.abort(); };
  }, []);
  async function refresh() { if (lock.current) return; const run = ++generation.current; setLoading(true); setMessage(''); try { const data = await api.accountSession(); if (!mounted.current || run !== generation.current) return; setUser(data.user); const snapshot = readCollection(); if (!data.user || snapshot?.owner !== data.user.id) { clearCollection(); setSaved([]); } const rows = data.user ? await api.favorites() : []; if (mounted.current && run === generation.current) { setSaved(rows); setCached(false); if (data.user && !saveCollection(data.user.id, rows)) setMessage('Favorites loaded, but offline storage is unavailable.'); } } catch (error) { if (mounted.current && run === generation.current) { setCached(true); setMessage('Connection unavailable. Showing the last collection; changes need a connection. ' + (error as Error).message); } } finally { if (mounted.current && run === generation.current) setLoading(false); } }
  useEffect(() => { const reconnect = () => { void refresh(); }; const cleared = () => { ++generation.current; setLoading(false); setSaved([]); setCached(false); setMessage('Offline copies cleared. Refresh to reopen your online collection.'); }; window.addEventListener('online', reconnect); window.addEventListener('spotland-offline-cleared', cleared); return () => { window.removeEventListener('online', reconnect); window.removeEventListener('spotland-offline-cleared', cleared); }; }, []);
  async function toggle(place: FavoritePlace) { if (!user) { setOpen(true); return; } if (lock.current) return; lock.current = true; setBusy(true); setMessage(''); const run = generation.current;
    if (!navigator.onLine || cached) { lock.current = false; setBusy(false); setMessage('Reconnect and refresh your account before changing favorites.'); return; }
    try { if (saved.some(row => row.place.id === place.id)) await api.removeFavorite(place.id); else await api.saveFavorite(place); const rows = await api.favorites(); if (mounted.current && run === generation.current) { setSaved(rows); setMessage(saveCollection(user.id, rows) ? 'Favorites updated and available offline.' : 'Favorites updated; offline storage is unavailable.'); } } catch (error) { if (mounted.current && run === generation.current) setMessage((error as Error).message); } finally { lock.current = false; if (mounted.current) setBusy(false); }
  }
  async function signOut() { if (lock.current) return; lock.current = true; setBusy(true); setMessage(''); ++generation.current; try { await api.logout(); if (mounted.current) { const cleared = clearCollection(); setCached(false); setUser(null); setSaved([]); setMessage(cleared ? 'Signed out on this browser.' : 'Signed out, but the browser blocked clearing offline copies. Clear site data on a shared device.'); } } catch (error) { if (mounted.current) setMessage((error as Error).message); } finally { lock.current = false; if (mounted.current) { setBusy(false); setLoading(false); } } }
  return <Context value={{ user, saved, cached, loading, busy, message, open, setOpen, refresh, toggle, signOut }}>{children}</Context>;
}


