import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { calendarRange, displayDate, indiaDate, type CalendarFilter } from '../../shared/calendar';
import { validateEvent, type EventRecord } from '../../shared/events';
import type { Place } from '../../shared/places';
import { googleMapsLink } from '../../shared/routes';
import { listEvents, listExternalEvents, moderateEvent, pendingEvents, submitEvent } from './events-api';
import { getModeratedPhoto, hideReview, moderateReviewPhoto, moderatedReviewPhotos, moderatedReviews, type ModeratedReview, type ModeratedReviewPhoto } from './reviews-api';
import type { ExternalEvents } from '../../shared/external-events';
const MapCanvas = lazy(() => import('./MapCanvas'));
export default function Events({ onClose, closeLabel = '← Home' }: { onClose: () => void; closeLabel?: string }) {
  const [filter, setFilter] = useState<CalendarFilter>('upcoming'); const [events, setEvents] = useState<EventRecord[]>([]); const [message, setMessage] = useState('Loading approved events…'); const [reload, setReload] = useState(0);
  const [now, setNow] = useState(Date.now()); const [view, setView] = useState<'list' | 'map'>('list'); const [selected, setSelected] = useState<Place | null>(null);
  const [busy, setBusy] = useState(false); const [submitMessage, setSubmitMessage] = useState(''); const [token, setToken] = useState(''); const [pending, setPending] = useState<EventRecord[]>([]); const [adminMessage, setAdminMessage] = useState('');
  const [adminReviews, setAdminReviews] = useState<ModeratedReview[]>([]); const [reviewMessage, setReviewMessage] = useState('');
  const [adminPhotos, setAdminPhotos] = useState<ModeratedReviewPhoto[]>([]); const [photoModerationMessage, setPhotoModerationMessage] = useState(''); const [photoPreviews, setPhotoPreviews] = useState<Record<string,string>>({}); const photoPreviewRef = useRef<Record<string,string>>({});
  const [external, setExternal] = useState<ExternalEvents | null>(null); const [externalMessage, setExternalMessage] = useState('Load the optional open-data feed when you want it.'); const [externalBusy, setExternalBusy] = useState(false);
  const externalAbort = useRef<AbortController | null>(null);
  const mounted = useRef(true); const range = calendarRange(filter, now); if (filter === 'upcoming') range.end = indiaDate(now + 365 * 86400000);
  useEffect(() => { mounted.current = true; const timer = window.setInterval(() => setNow(Date.now()), 60000); return () => { mounted.current = false; window.clearInterval(timer); }; }, []);
  useEffect(() => () => externalAbort.current?.abort(), []);
  useEffect(() => () => { Object.values(photoPreviewRef.current).forEach(URL.revokeObjectURL); }, []);
  useEffect(() => {
    const controller = new AbortController(); setEvents([]); setSelected(null); setMessage('Loading approved events…');
    listEvents(range.start, range.end, controller.signal).then(data => { if (!controller.signal.aborted) { setEvents(data); setMessage(`${data.length} approved events. Check details with the organiser.`); } }).catch(error => { if (!controller.signal.aborted) setMessage(error.message); });
    return () => controller.abort();
  }, [range.start, range.end, reload]);
  const onMove = useCallback(() => {}, []);
  const visibleExternal = external?.events.filter(event => event.date >= range.start && event.date <= range.end) || [];
  const places: Place[] = [...events.map(event => ({ ...event, category: 'attraction' as const, hours: displayDate(event.date) })), ...visibleExternal.filter(event => event.point).map(event => ({ id: event.id, name: event.name, address: event.location, category: 'attraction' as const, hours: displayDate(event.date), ...event.point! }))];
  async function loadExternal() {
    if (externalBusy) return; const controller = new AbortController(); externalAbort.current = controller; setExternalBusy(true); setExternalMessage('Checking Wikidata…');
    try { const data = await listExternalEvents(controller.signal); if (!controller.signal.aborted) { setExternal(data); setSelected(null); setExternalMessage(data.events.length ? 'Open-data events loaded. Confirm with the organiser before going.' : 'No dated events returned by Wikidata. Coverage is sparse; this does not mean there are no events.'); } }
    catch (error) { if (!controller.signal.aborted) setExternalMessage((error as Error).message); }
    finally { if (!controller.signal.aborted) setExternalBusy(false); }
  }
  async function submit(formEvent: React.FormEvent<HTMLFormElement>) {
    formEvent.preventDefault(); if (busy) return; const form = formEvent.currentTarget; const values = new FormData(form); setBusy(true);
    try { const event = validateEvent({ name: values.get('name'), date: values.get('date'), address: values.get('address'), description: values.get('description'), lat: Number(values.get('lat')), lon: Number(values.get('lon')) }); await submitEvent(event); if (mounted.current) { setSubmitMessage('Submitted for review. It appears publicly only after approval.'); form.reset(); } }
    catch (error) { if (mounted.current) setSubmitMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); }
  }
  async function loadPending() { try { const rows = await pendingEvents(token); if (mounted.current) { setPending(rows); setAdminMessage(`${rows.length} pending submissions.`); } } catch (error) { if (mounted.current) { setPending([]); setAdminMessage((error as Error).message); } } }
  async function moderate(id: string, status: 'approved' | 'rejected') { if (busy) return; setBusy(true); try { await moderateEvent(id, status, token); if (mounted.current) { setPending(rows => rows.filter(row => row.id !== id)); setReload(value => value + 1); setAdminMessage(`Submission ${status}.`); } } catch (error) { if (mounted.current) setAdminMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  async function loadAdminReviews() { try { const rows = await moderatedReviews(token); if (mounted.current) { setAdminReviews(rows); setReviewMessage(`${rows.length} recent review${rows.length === 1 ? '' : 's'} loaded (maximum 50).`); } } catch (error) { if (mounted.current) { setAdminReviews([]); setReviewMessage((error as Error).message); } } }
  async function moderateReview(review: ModeratedReview) { if (busy) return; setBusy(true); try { await hideReview(review.id,token); if (mounted.current) { setAdminReviews(rows => rows.map(row => row.id === review.id ? { ...row,status:'hidden' } : row)); setReviewMessage('Review hidden from public lists and rating averages.'); } } catch (error) { if (mounted.current) setReviewMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  function clearPhotoPreviews() { Object.values(photoPreviewRef.current).forEach(URL.revokeObjectURL); photoPreviewRef.current={}; setPhotoPreviews({}); }
  async function loadAdminPhotos() { try { const rows=await moderatedReviewPhotos(token); if (mounted.current) { setAdminPhotos(rows); setPhotoModerationMessage(`${rows.length} pending or reported photos.`); } } catch(error) { if (mounted.current) { setAdminPhotos([]); setPhotoModerationMessage((error as Error).message); } } }
  async function previewAdminPhoto(id:string) { if (busy || photoPreviews[id]) return; setBusy(true); try { const url=await getModeratedPhoto(id,token); if (mounted.current) { photoPreviewRef.current[id]=url; setPhotoPreviews(current=>({...current,[id]:url})); } else URL.revokeObjectURL(url); } catch(error) { if (mounted.current) setPhotoModerationMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  async function moderatePhoto(photo:ModeratedReviewPhoto,action:'approve'|'hide'|'delete') { if (busy) return; if (action==='delete'&&!window.confirm('Permanently delete this uploaded photo? This cannot be undone.')) return; setBusy(true); try { await moderateReviewPhoto(photo.id,action,token); if (mounted.current) { if (action==='delete'||action==='approve') { const url=photoPreviewRef.current[photo.id]; if (url) URL.revokeObjectURL(url); delete photoPreviewRef.current[photo.id]; setPhotoPreviews(current=>{const next={...current};delete next[photo.id];return next;}); setAdminPhotos(rows=>rows.filter(row=>row.id!==photo.id)); } else setAdminPhotos(rows=>rows.map(row=>row.id===photo.id?{...row,status:'hidden'}:row)); setPhotoModerationMessage(action==='delete'?'Photo permanently deleted.':`Photo ${action==='approve'?'approved': 'hidden'}; list status updated.`); } } catch(error) { if (mounted.current) setPhotoModerationMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  return <section className="special-days" aria-label="Community events"><header className="explore-header"><button onClick={onClose}>{closeLabel}</button><strong>Plans from the neighbourhood</strong></header><div className="calendar-content"><h1>What’s happening?</h1><p>Community submissions, reviewed before publication. No login required to browse or submit.</p>
    <div className="calendar-filters">{(['today', 'weekend', 'upcoming'] as const).map(value => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value === 'today' ? 'Today' : value === 'weekend' ? 'This weekend' : 'Upcoming'}</button>)}<button aria-pressed={view === 'list'} onClick={() => setView('list')}>List</button><button aria-pressed={view === 'map'} onClick={() => setView('map')}>Map</button><button onClick={() => setReload(value => value + 1)}>Refresh events</button></div><p role="status">{message}</p>
    {view === 'map' && places.length > 0 && <div className="event-map"><Suspense fallback={<p>Loading event map…</p>}><MapCanvas center={places[0]} places={places} onMove={onMove} onSelect={setSelected}/></Suspense></div>}
    {view === 'map' && <p>© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a> · Community pins use submitted public venues. Wikidata pins require explicit event coordinates; verify their accuracy. Events without coordinates stay in the list. Events across India may require zooming out.</p>}
    {selected && <div className="calendar-note"><button onClick={() => setSelected(null)}>Close event details</button><span className="eyebrow">{selected.id.startsWith('wikidata:') ? 'WIKIDATA · OPEN DATA' : 'COMMUNITY · REVIEWED'}</span><h2>{selected.name}</h2><p>{selected.address} · {selected.hours}</p><a href={googleMapsLink(selected, 'drive')} target="_blank" rel="noreferrer">Directions ↗</a>{visibleExternal.find(event => event.id === selected.id) && <a href={visibleExternal.find(event => event.id === selected.id)!.sourceUrl} target="_blank" rel="noreferrer">Verify on Wikidata ↗</a>}</div>}
    {!events.length && <p>No approved events in this view yet.</p>}<ul className="calendar-cards">{events.map(event => <li key={event.id}><span className="eyebrow">COMMUNITY · REVIEWED</span><h2>{event.name}</h2><time dateTime={event.date}>{displayDate(event.date)}</time><p>{event.address}</p><p>{event.description}</p><a href={googleMapsLink(event, 'drive')} target="_blank" rel="noreferrer">Directions ↗</a></li>)}</ul>
    <section aria-label="External events"><h2>A little extra from Wikidata</h2><p>Optional community-maintained open data from Wikidata’s official API. Sparse coverage of dated festivals, concerts, exhibitions and sports competitions in India; not organiser-confirmed or moderator-approved. No ticket listings are copied.</p><button onClick={() => void loadExternal()} disabled={externalBusy}>{externalBusy ? 'Loading external events…' : external ? 'Refresh Wikidata events' : 'Load Wikidata events'}</button><p role="status">{externalMessage}</p>
      {external && <><p>Last checked: {new Intl.DateTimeFormat('en-IN', { timeZone: 'Asia/Kolkata', dateStyle: 'medium', timeStyle: 'short' }).format(external.fetchedAt)} IST. Results are cached for six hours.</p><p>{external.coverage}</p>{!visibleExternal.length && <p>No Wikidata events match this date filter.</p>}<ul className="calendar-cards">{visibleExternal.map(event => <li key={event.id}><span className="eyebrow">WIKIDATA · OPEN DATA · CC0</span><h2>{event.name}</h2><time dateTime={event.date}>{displayDate(event.date)} · start date</time><p>{event.location}</p><a href={event.sourceUrl} target="_blank" rel="noreferrer">Verify / report a data issue on Wikidata ↗</a>{event.point ? <a href={googleMapsLink(event.point, 'drive')} target="_blank" rel="noreferrer">Directions to mapped event location ↗</a> : <p>No event coordinates supplied; no map pin.</p>}</li>)}</ul></>}
    </section>
    <details><summary>Add a public event</summary><p>Submit only public venue details. Do not include private contact details, home addresses or copied listings. A moderator reviews content; approval is not a guarantee the event will take place.</p><form className="event-form" onSubmit={submit}><label>Event name<input name="name" required minLength={3} maxLength={100}/></label><label>Date (IST)<input name="date" type="date" required min={indiaDate()} max={indiaDate(Date.now() + 365 * 86400000)}/></label><label>Public venue address<input name="address" required minLength={5} maxLength={200}/></label><label>Latitude<input name="lat" type="number" min={6} max={38} step="any" required/></label><label>Longitude<input name="lon" type="number" min={68} max={98} step="any" required/></label><label>Description<textarea name="description" required minLength={10} maxLength={600}/></label><button disabled={busy}>{busy ? 'Sending…' : 'Submit for review'}</button><p role="status">{submitMessage}</p></form></details>
    <details><summary>Moderator access</summary><p>Operator-only token. It stays in memory and is cleared when you leave.</p><label>Moderator token<input type="password" autoComplete="off" value={token} onChange={event => { setToken(event.target.value); setPending([]); setAdminReviews([]); setAdminPhotos([]); setAdminMessage(''); setReviewMessage(''); setPhotoModerationMessage(''); clearPhotoPreviews(); }}/></label><button disabled={!token || busy} onClick={loadPending}>Load pending submissions</button><p role="status">{adminMessage}</p><ul>{pending.map(event => <li key={event.id}><h3>{event.name}</h3><p>{event.date} · {event.address} · {event.lat}, {event.lon}</p><p>{event.description}</p><button disabled={busy} onClick={() => moderate(event.id, 'approved')}>Approve {event.name}</button><button disabled={busy} onClick={() => moderate(event.id, 'rejected')}>Reject {event.name}</button></li>)}</ul></details>
    <details><summary>Traveller review moderation</summary><p>Requires the same operator-only token. Shows at most the latest 50 reviews without author names or account IDs. Hiding removes a review from public lists and rating averages; a hidden review cannot be restored here.</p><button disabled={!token || busy} onClick={() => void loadAdminReviews()}>Load recent reviews</button><p role="status">{reviewMessage}</p><ul>{adminReviews.map(review => <li key={review.id}><h3>{review.rating}/5 · {review.status} · {review.reports} report{review.reports === 1 ? '' : 's'}</h3><p>Place: {review.placeId}</p><p className="review-text">{review.text}</p><small>Updated {new Date(review.updatedAt).toLocaleDateString('en-IN')}</small>{review.status === 'visible' && <button disabled={busy} onClick={() => void moderateReview(review)}>Hide review</button>}</li>)}</ul></details>
    <details><summary>Traveller photo moderation</summary><p>New and three-report-hidden photos are private to the uploader until approved. Preview loads with the in-memory operator token. Delete permanently removes the R2 object.</p><button disabled={!token || busy} onClick={() => void loadAdminPhotos()}>Load pending and reported photos</button><p role="status">{photoModerationMessage}</p><ul>{adminPhotos.map(photo=><li key={photo.id}><h3>{photo.status==='hidden'?'Reported / hidden':'Pending'} · {photo.rating}/5 · {photo.reports} report{photo.reports===1?'':'s'}</h3><p>Place: {photo.placeId} · Review: {photo.text}</p><small>Submitted {new Date(photo.createdAt).toLocaleDateString('en-IN')}</small>{photoPreviews[photo.id]?<img className="moderation-photo-preview" src={photoPreviews[photo.id]} alt="Private photo preview for moderation"/>:<button disabled={busy} onClick={()=>void previewAdminPhoto(photo.id)}>Load private preview</button>}<button disabled={busy} onClick={()=>void moderatePhoto(photo,'approve')}>Approve photo</button><button disabled={busy} onClick={()=>void moderatePhoto(photo,'hide')}>Hide photo</button><button disabled={busy} onClick={()=>void moderatePhoto(photo,'delete')}>Delete photo</button></li>)}</ul></details>
  </div></section>;
}

