import { contactList, type EmergencyContact } from '../../shared/sos';
import type { SosIntent } from './sos-api';
async function database() { return new Promise<IDBDatabase>((resolve,reject) => { const r = indexedDB.open('spotland-safety',1); r.onupgradeneeded = () => r.result.createObjectStore('private'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(new Error('On-device safety storage is unavailable.')); }); }
async function read(key: string): Promise<unknown> { const db = await database(); return new Promise((resolve,reject) => { const tx = db.transaction('private','readonly'), r = tx.objectStore('private').get(key); let value: unknown; r.onsuccess = () => { value = r.result; }; tx.oncomplete = () => { db.close(); resolve(value); }; tx.onabort = () => { db.close(); reject(new Error('Could not read device safety data.')); }; tx.onerror = () => reject(new Error('Could not read device safety data.')); }); }
async function write(key: string, value: unknown) { const db = await database(); return new Promise<void>((resolve,reject) => { const tx = db.transaction('private','readwrite'); if (value === null) tx.objectStore('private').delete(key); else tx.objectStore('private').put(value,key); tx.oncomplete = () => { db.close(); resolve(); }; tx.onabort = () => { db.close(); reject(new Error('Safety data was not saved on this device.')); }; tx.onerror = () => reject(new Error('Safety data was not saved on this device.')); }); }
export const getContacts = async () => contactList(await read('contacts') || []);
export const saveContacts = (contacts: EmergencyContact[]) => write('contacts',contactList(contacts));
export const saveSosIntent = (intent: SosIntent | null) => write('pending-sos',intent);
export async function getSosIntent(): Promise<SosIntent | null> { const v = await read('pending-sos') as SosIntent | null; if (!v) return null; if (!/^[a-f0-9-]{36}$/.test(v.id) || !/^[a-f0-9-]{36}$/.test(v.shareId) || !/^[A-Za-z0-9_-]{43}$/.test(v.shareNonce) || !Number.isFinite(v.startedAt) || typeof v.broadcast !== 'boolean' || typeof v.closing !== 'boolean' || !Number.isFinite(v.shareExpiresAt) || v.geohash !== undefined && !/^[0-9bcdefghjkmnpqrstuvwxyz]{6}$/.test(v.geohash)) throw new Error('Stored SOS data is invalid. Use Call 112 and clear the pending SOS.'); return v; }
