import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { indiaDate } from '../../shared/calendar';
import { moveStop, tripDayHours, validateTrip, maxTripStops, type SavedTrip, type TripInput, type TripStop } from '../../shared/trips';
import { formatDistance, formatDuration, travelModes, type Route } from '../../shared/routes';
import { conditions, weatherTime, type Forecast } from '../../shared/weather';
import { weatherAlerts } from '../../shared/weather-score';
import type { Place, SearchResult } from '../../shared/places';
import { searchLocation } from './explore-api';
import { fetchWeather } from './weather-api';
import { tripRoute, savedTrips, reopenTrip, saveTrip, removeTrip } from './trips-api';
import { useAccount } from './AccountContext';
import { TripConfetti } from './PlayfulExtras';
const MapCanvas = lazy(() => import('./MapCanvas'));
export default function TripPlanner({ onClose }: { onClose: () => void }) {
  const account = useAccount();
  const [celebration, setCelebration] = useState(0);
  const [plan, setPlan] = useState<TripInput>({name:'My little detour',date:indiaDate(),mode:'walk',stops:[]});
  const [query, setQuery] = useState(''), [results, setResults] = useState<SearchResult[]>([]), [searching, setSearching] = useState(false), [searchMessage, setSearchMessage] = useState('Search when ready; no queries are sent as you type.');
  const [stopName, setStopName] = useState(''), [lat, setLat] = useState(''), [lon, setLon] = useState('');
  const [route, setRoute] = useState<Route | null>(null), [forecast, setForecast] = useState<Forecast | null>(null), [weatherMessage, setWeatherMessage] = useState('Calculate your trip to check the sky at its starting point.');
  const [message, setMessage] = useState('Add your starting point, then the places you want to visit.'), [busy, setBusy] = useState(false), [collection, setCollection] = useState<Omit<SavedTrip,'stops'>[]>([]), [collectionMessage, setCollectionMessage] = useState(''), [collectionBusy, setCollectionBusy] = useState(false);
  const mounted = useRef(true), controller = useRef<AbortController | null>(null), searchController = useRef<AbortController | null>(null), collectionController = useRef<AbortController | null>(null), attempt = useRef<string | null>(null), lock = useRef(false), heading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { mounted.current = true; heading.current?.focus(); return () => { mounted.current = false; controller.current?.abort(); searchController.current?.abort(); collectionController.current?.abort(); }; }, []);
  useEffect(() => { setCollection([]); setCollectionMessage(''); if (account.user) void refreshCollection(); else collectionController.current?.abort(); return () => collectionController.current?.abort(); }, [account.user?.id]);
  function edit(next: TripInput) { controller.current?.abort(); setPlan(next); setRoute(null); setForecast(null); setWeatherMessage('Trip changed. Calculate again for this order and day.'); attempt.current = null; setMessage('Draft changed; saved trips stay unchanged.'); }
  function add(stop: TripStop) { if (plan.stops.length >= maxTripStops) { setMessage('Eight stops max for this pilot.'); return; } edit({...plan,stops:[...plan.stops,stop]}); }
  async function search() {
    searchController.current?.abort(); const c = new AbortController(); searchController.current = c; setSearching(true); setResults([]); setSearchMessage('Looking for that spot…');
    try { const rows = await searchLocation(query.trim(),c.signal); if (!c.signal.aborted) { setResults(rows); setSearchMessage(rows.length ? 'Choose a result to add it. © OpenStreetMap contributors' : 'No matches. Try a landmark plus its city, or enter coordinates.'); } } catch (e) { if (!c.signal.aborted) setSearchMessage((e as Error).message); } finally { if (!c.signal.aborted) setSearching(false); }
  }
  async function calculate() {
    if (lock.current) return;
    let trip; try { trip = validateTrip(plan); } catch (e) { setMessage((e as Error).message); return; }
    lock.current = true; setBusy(true); setRoute(null); setForecast(null); setMessage('Drawing the whole route in your chosen order…'); setWeatherMessage('Checking weather at the starting point…'); const c = new AbortController(); controller.current = c;
    const inForecastRange = trip.date >= indiaDate() && trip.date <= indiaDate(Date.now() + 2 * 86400000);
    const weather = inForecastRange ? fetchWeather(trip.stops[0].lat,trip.stops[0].lon,c.signal).then(f => { if (!c.signal.aborted && mounted.current) { setForecast(f); setWeatherMessage(tripDayHours(f,trip.date).length ? 'Hourly forecast at the starting point. Times are IST; weather elsewhere may differ.' : 'No remaining forecast hours for this day. This provider covers today and the next two days; saved future trips can be checked nearer departure.'); } }).catch(e => { if (!c.signal.aborted && mounted.current) setWeatherMessage(`Weather unavailable: ${(e as Error).message}`); }) : Promise.resolve(setWeatherMessage('No remaining forecast hours for this day. This provider covers today and the next two days; saved future trips can be checked nearer departure.'));
    try { const r = await tripRoute(trip,c.signal); if (!c.signal.aborted && mounted.current) { setRoute(r); setMessage('Full route ready. Travel time excludes stop visits, traffic and delays.'); } } catch (e) { if (!c.signal.aborted && mounted.current) setMessage(`Route unavailable: ${(e as Error).message} Your itinerary is still here.`); } finally { await weather; lock.current = false; if (mounted.current) setBusy(false); }
  }
  async function refreshCollection() {
    collectionController.current?.abort(); const c = new AbortController(); collectionController.current = c; setCollectionBusy(true);
    try { const rows = await savedTrips(c.signal); if (!c.signal.aborted && mounted.current) { setCollection(rows); setCollectionMessage(rows.length ? 'Reopen a trip, then calculate to refresh its route and weather.' : 'No saved trips yet. Your next detour can be the first.'); } } catch (e) { if (!c.signal.aborted && mounted.current) setCollectionMessage((e as Error).message); } finally { if (!c.signal.aborted && mounted.current) setCollectionBusy(false); }
  }
  async function save() {
    if (lock.current) return; if (!account.user) { account.setOpen(true); return; }
    let trip; try { trip = validateTrip(plan); } catch (e) { setMessage((e as Error).message); return; }
    lock.current = true; setBusy(true); const c = new AbortController(); controller.current = c; const id = attempt.current || crypto.randomUUID(); attempt.current = id;
    try { await saveTrip(id,trip,c.signal); if (!c.signal.aborted && mounted.current) { setMessage('Trip saved. Your ordered itinerary is in your collection.'); setCelebration(value => value + 1); await refreshCollection(); } } catch (e) { if (!c.signal.aborted && mounted.current) setMessage(`Save NOT confirmed: ${(e as Error).message} Retry the same draft to check this save.`); } finally { lock.current = false; if (mounted.current) setBusy(false); }
  }
  async function open(id: string) {
    if (lock.current) return; lock.current = true; setBusy(true); const c = new AbortController(); controller.current = c;
    try { const trip = await reopenTrip(id,c.signal); if (!c.signal.aborted && mounted.current) { edit({name:trip.name,date:trip.date,mode:trip.mode,stops:trip.stops}); setMessage('Trip reopened. Calculate to refresh route/weather; edits save as a new trip.'); } } catch (e) { if (!c.signal.aborted && mounted.current) setMessage((e as Error).message); } finally { lock.current = false; if (mounted.current) setBusy(false); }
  }
  async function remove(id: string) { if (lock.current) return; lock.current = true; setBusy(true); const c = new AbortController(); controller.current = c; try { await removeTrip(id,c.signal); if (!c.signal.aborted && mounted.current) { setCollectionMessage('Saved trip removed. The current draft is unchanged.'); await refreshCollection(); } } catch (e) { if (!c.signal.aborted && mounted.current) setCollectionMessage(`Remove NOT confirmed: ${(e as Error).message}`); } finally { lock.current = false; if (mounted.current) setBusy(false); } }
  const hours = forecast ? tripDayHours(forecast,plan.date) : [];
  const markers: Place[] = plan.stops.map((s,i) => ({...s,id:`trip-${i}`,name:`${i+1}. ${s.name}`,category:'attraction',hours:''}));
  return <section className="special-days trip-planner" aria-label="Trip planner"><header className="explore-header"><button onClick={onClose}>← Home</button><strong>SPOTLAND / TRIP POSTCARD</strong></header><div className="trip-content"><span className="eyebrow">ONE DAY. A FEW GOOD DETOURS.</span><h1 ref={heading} tabIndex={-1}>Chalo, make a plan.</h1><p>First stop = starting point. Up to eight stops, each within 100 km of the start. Planning works without login; sign in to save.</p><p role="status">{message}</p><TripConfetti celebration={celebration}/>
    <p>Unsaved drafts stay in this screen. Going Home or refreshing discards them.</p><div className="trip-fields"><label>Trip name<input value={plan.name} maxLength={100} disabled={busy} onChange={e => edit({...plan,name:e.target.value})}/></label><label>Trip day (IST)<input type="date" value={plan.date} disabled={busy} onInput={e => edit({...plan,date:e.currentTarget.value})} onChange={e => edit({...plan,date:e.target.value})}/></label><label>Travel mode<select value={plan.mode} disabled={busy} onChange={e => edit({...plan,mode:e.target.value as TripInput['mode']})}>{travelModes.map(m => <option key={m} value={m}>{m}</option>)}</select></label></div>
    <h2>Your stops, your order</h2>{!plan.stops.length && <p>The postcard is blank. Add a starting point below.</p>}<ol className="trip-stops">{plan.stops.map((s,i) => <li key={`${i}-${s.name}`}><strong>{i+1}. {s.name}</strong><p>{s.address}</p><div className="share-actions"><button disabled={busy || i===0} aria-label={`Move ${s.name} up`} onClick={() => edit({...plan,stops:moveStop(plan.stops,i,-1)})}>↑ Up</button><button disabled={busy || i===plan.stops.length-1} aria-label={`Move ${s.name} down`} onClick={() => edit({...plan,stops:moveStop(plan.stops,i,1)})}>↓ Down</button><button disabled={busy} aria-label={`Remove stop ${s.name}`} onClick={() => edit({...plan,stops:plan.stops.filter((_,index) => index!==i)})}>Remove</button></div></li>)}</ol>
    <h2>Add a spot</h2><form className="place-search" onSubmit={e => {e.preventDefault();void search();}}><label className="sr-only" htmlFor="trip-search">Search a landmark or address</label><input id="trip-search" value={query} minLength={2} maxLength={120} required disabled={busy || searching} onChange={e => {setQuery(e.target.value);setResults([]);}} placeholder="Landmark + city, e.g. India Gate Delhi"/><button disabled={busy || searching}>Search spots</button></form><p role="status">{searchMessage}</p><div className="trip-results">{results.map((r,i) => <button key={i} disabled={busy || plan.stops.length>=8} onClick={() => {add({name:r.name.split(',')[0].slice(0,120),address:r.name.slice(0,300),lat:r.lat,lon:r.lon});setResults([]);}}>{r.name} — Add stop</button>)}</div>
    {account.saved.some(f => f.place.lat!==undefined && f.place.lon!==undefined) && <details><summary>Add from favorites</summary>{account.saved.filter(f => f.place.lat!==undefined && f.place.lon!==undefined).map(f => <button key={f.place.id} disabled={busy || plan.stops.length>=8} onClick={() => add({name:f.place.name,address:f.place.address,lat:f.place.lat!,lon:f.place.lon!})}>Add {f.place.name}</button>)}</details>}
    <details><summary>Add a named stop by coordinates</summary><form className="trip-fields" onSubmit={e => {e.preventDefault();if(!lat.trim() || !lon.trim()){setMessage('Enter both coordinates.');return;}const s={name:stopName.trim(),address:'Entered coordinates',lat:Number(lat),lon:Number(lon)};if(!s.name || !Number.isFinite(s.lat) || !Number.isFinite(s.lon) || s.lat<6 || s.lat>38 || s.lon<68 || s.lon>98){setMessage('Enter a name and valid coordinates in India.');return;}add(s);setStopName('');setLat('');setLon('');}}><label>Stop name<input value={stopName} maxLength={120} required disabled={busy} onChange={e=>setStopName(e.target.value)}/></label><label>Latitude<input type="number" step="any" min="6" max="38" value={lat} required disabled={busy} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input type="number" step="any" min="68" max="98" value={lon} required disabled={busy} onChange={e=>setLon(e.target.value)}/></label><button disabled={busy || plan.stops.length>=8}>Add coordinate stop</button></form></details>
    <div className="share-actions"><button className="button" disabled={busy || plan.stops.length<2} onClick={() => void calculate()}>Calculate full trip</button><button disabled={busy || account.loading || plan.stops.length<2} onClick={() => void save()}>{account.user ? 'Save as new trip' : 'Sign in to save trip'}</button>{busy && <button onClick={() => {controller.current?.abort();setMessage('Request cancelled. A save may still have reached the server; refresh your collection to check.');}}>Cancel request</button>}</div><p>Calculation sends rounded stop coordinates to our cached routing/weather providers. Saving stores the ordered coordinates in your private account. Route times are estimates, with no live traffic or time spent at stops.</p>
    {route && <><h2>Full route · {formatDistance(route.distance)} · {formatDuration(route.duration)}</h2><div className="trip-map"><Suspense fallback={<p>Loading route map…</p>}><MapCanvas center={plan.stops[0]} places={markers} route={route} onMove={() => {}} onSelect={p=>setMessage(p.name)}/></Suspense></div><p>© OpenStreetMap contributors · <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noreferrer">Fix the map</a></p><details><summary>Turn-by-turn route ({route.steps.length} steps)</summary><ol>{route.steps.map((s,i)=><li key={i}>{s.instruction} · {formatDistance(s.distance)}</li>)}</ol></details></>}
    <h2>Sky check · {plan.date} (IST)</h2><p role="status">{weatherMessage}</p>{forecast && <p>Forecast fetched {weatherTime(forecast.fetchedAt)}. No historical weather or invented forecasts.</p>}{hours.length>0 && <div className="trip-hourly" tabIndex={0} role="region" aria-label="Trip day hourly weather"><table><thead><tr><th>Time (IST)</th><th>Weather</th><th>°C</th><th>Rain chance</th><th>Wind</th></tr></thead><tbody>{hours.map(h=><tr key={h.time}><th>{weatherTime(h.time)}</th><td>{conditions(h.code)}{weatherAlerts(h).map(a=><p key={a}>{a}</p>)}</td><td>{h.temperature}°</td><td>{h.rainChance}%</td><td>{h.wind} km/h</td></tr>)}</tbody></table></div>}
    <h2>Your saved postcards</h2>{account.user ? <><button disabled={busy || collectionBusy} onClick={() => void refreshCollection()}>Refresh saved trips</button><p role="status">{collectionMessage}</p><p>50 saved trips per account. Reopened edits save as a new trip; originals stay unchanged.</p><div className="calendar-cards">{collection.map(t=><article key={t.id}><h3>{t.name}</h3><p>{t.date} · {t.mode}</p><button disabled={busy} onClick={()=>void open(t.id)}>Reopen {t.name}</button><button disabled={busy} onClick={()=>void remove(t.id)}>Remove saved trip {t.name}</button></article>)}</div></> : <p>Sign in through Account &amp; favorites to save and reopen your itinerary.</p>}</div></section>;
}
