import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { venueKinds, validateVenue, type Venue, type VenueKind } from '../../shared/venues';
import { cityBookingLinks } from '../../shared/booking-providers';
import { distanceKm, type Place, type SearchResult } from '../../shared/places';
import { googleMapsLink } from '../../shared/routes';
import { searchLocation } from './explore-api';
import { listVenues, submitVenue, reportPrice, pendingVenues, venueReports, moderateVenue, resolveReport } from './venues-api';
import Crowd from './Crowd';
import FavoriteButton from './FavoriteButton';
const Reviews = lazy(() => import('./Reviews'));
const MapCanvas = lazy(() => import('./MapCanvas')); const Events = lazy(() => import('./Events'));
const pilots = [{ city: 'Delhi', lat: 28.6139, lon: 77.209 }, { city: 'Mumbai', lat: 18.9388, lon: 72.8354 }, { city: 'Bengaluru', lat: 12.9716, lon: 77.5946 }];
export default function Venues({ onClose }: { onClose: () => void }) {
  const [area, setArea] = useState(pilots[0]); const [venues, setVenues] = useState<Venue[]>([]); const [selected, setSelected] = useState<Venue | null>(null); const [kind, setKind] = useState<VenueKind | ''>(''); const [view, setView] = useState<'list' | 'map'>('list');
  const [message, setMessage] = useState('Loading venues…'); const [loading, setLoading] = useState(false); const [reload, setReload] = useState(0); const [showEvents, setShowEvents] = useState(false);
  const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchResult[]>([]); const [searching, setSearching] = useState(false); const searchAbort = useRef<AbortController | null>(null); const lastSearch = useRef(0);
  const [busy, setBusy] = useState(false); const [formMessage, setFormMessage] = useState(''); const [reportMessage, setReportMessage] = useState('');
  const [token, setToken] = useState(''); const tokenRef = useRef(''); const [pending, setPending] = useState<Venue[]>([]); const [reports, setReports] = useState<{id:string;venue_id:string;reason:string}[]>([]); const [adminMessage, setAdminMessage] = useState(''); const mounted = useRef(true);
  const detailClose = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (selected) { setReportMessage(''); detailClose.current?.focus(); detailClose.current?.scrollIntoView({ block: 'center', behavior: 'auto' }); } }, [selected]);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; searchAbort.current?.abort(); }; }, []);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setVenues([]); setSelected(null); setMessage('Loading venues…'); listVenues(area.lat, area.lon, area.city, controller.signal).then(data => { if (!controller.signal.aborted) { setVenues(data.venues); setMessage(data.warning || `${data.venues.length} venues and pilot picks. Confirm details with the venue.`); } }).catch(error => { if (!controller.signal.aborted) setMessage(error.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [area, reload]);
  const visible = venues.filter(venue => !kind || venue.kind === kind); const mapped: Place[] = visible.filter(venue => venue.lat !== undefined && venue.lon !== undefined).map(venue => ({ id: venue.id, name: venue.name, lat: venue.lat!, lon: venue.lon!, category: venue.kind === 'gaming' ? 'gaming' : 'attraction', address: venue.address, hours: venue.hours }));
  const onMove = useCallback(() => {}, []); const onSelect = useCallback((place: Place) => setSelected(venues.find(venue => venue.id === place.id) || null), [venues]);
  function chooseVenue(venue: Venue) { setSelected(venue); setReportMessage(''); }
  async function search(event: React.FormEvent) { event.preventDefault(); if (searching || query.trim().length < 2 || Date.now() - lastSearch.current < 1500) return; lastSearch.current = Date.now(); searchAbort.current?.abort(); const controller = new AbortController(); searchAbort.current = controller; setSearching(true); setResults([]); try { const rows = await searchLocation(query, controller.signal); if (!controller.signal.aborted) { setResults(rows); if (!rows.length) setMessage('No matching Indian city or landmark.'); } } catch (error) { if (!controller.signal.aborted) setMessage((error as Error).message); } finally { if (!controller.signal.aborted) setSearching(false); } }
  async function add(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; const form = event.currentTarget; const values = new FormData(form); setBusy(true); try { const otherUrl = String(values.get('booking_url') || ''); const input = validateVenue({ name: values.get('name'), kind: values.get('kind'), city: values.get('city'), address: values.get('address'), hours: values.get('hours'), phone: values.get('phone'), website: values.get('website'), lat: Number(values.get('lat')), lon: Number(values.get('lon')), price_note: values.get('price_note'), booking_links: otherUrl ? [{ label: values.get('booking_label'), url: otherUrl }] : [] }); await submitVenue(input); if (mounted.current) { setFormMessage('Submitted for review. Hidden until approved.'); form.reset(); } } catch (error) { if (mounted.current) setFormMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  async function priceReport(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected || busy) return; const form = event.currentTarget; setBusy(true); try { await reportPrice(selected.id, String(new FormData(form).get('reason'))); if (mounted.current) { setReportMessage('Reported for review. Published prices are not changed automatically.'); form.reset(); } } catch (error) { if (mounted.current) setReportMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  async function loadAdmin() { if (busy) return; const usedToken = token; setBusy(true); try { const rows = await Promise.all([pendingVenues(usedToken), venueReports(usedToken)]); if (mounted.current && tokenRef.current === usedToken) { setPending(rows[0]); setReports(rows[1]); setAdminMessage('Pending venues and price reports loaded.'); } } catch (error) { if (mounted.current && tokenRef.current === usedToken) setAdminMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  async function moderate(id: string, status: 'approved' | 'rejected' | 'resolved') { if (busy) return; setBusy(true); try { if (status === 'resolved') await resolveReport(id, token); else await moderateVenue(id, status, token); if (mounted.current) { setPending(rows => rows.filter(row => row.id !== id)); setReports(rows => rows.filter(row => row.id !== id)); setReload(value => value + 1); setAdminMessage(`Marked ${status}.`); } } catch (error) { if (mounted.current) setAdminMessage((error as Error).message); } finally { if (mounted.current) setBusy(false); } }
  if (showEvents) return <Suspense fallback={<p>Loading what’s on…</p>}><Events onClose={() => setShowEvents(false)} closeLabel="← Venues"/></Suspense>;
  return <section className="special-days" aria-label="Entertainment venues"><header className="explore-header"><button onClick={onClose}>← Home</button><strong>Plans with a plot twist</strong></header><div className="calendar-content"><h1>Screen time, stage time, play time.</h1><p>Cinemas, theatres, comedy clubs, gaming spaces and workshops. Browse freely; bookings happen on the provider’s site.</p>
    <div className="calendar-filters">{pilots.map(pilot => <button key={pilot.city} aria-pressed={area.city === pilot.city} onClick={() => setArea(pilot)}>{pilot.city}</button>)}<button onClick={() => setReload(value => value + 1)} disabled={loading}>Refresh venues</button></div>
    <form className="place-search" onSubmit={search}><label className="sr-only" htmlFor="venue-search">Search venue area in India</label><input id="venue-search" value={query} onChange={event => setQuery(event.target.value)} maxLength={120} placeholder="Search a city or landmark"/><button disabled={searching || query.trim().length < 2}>{searching ? 'Searching…' : 'Search area'}</button></form>{results.map((result, index) => <button key={index} onClick={() => { setArea({ lat: result.lat, lon: result.lon, city: result.name.split(',')[0] }); setResults([]); }}>{result.name}</button>)}
    <p className="location-note">Search sends your submitted area to our cached geocoder. OSM venues cover 5 km around the selected area. Pilot-city picks may have no coordinates; distance is unknown.</p><label>Venue type<select value={kind} onChange={event => setKind(event.target.value as VenueKind | '')}><option value="">All types</option>{venueKinds.map(value => <option key={value}>{value}</option>)}</select></label><div className="calendar-filters"><button aria-pressed={view === 'list'} onClick={() => setView('list')}>List</button><button aria-pressed={view === 'map'} onClick={() => setView('map')}>Map</button></div><p role="status">{message}</p>
    {view === 'map' && <><div className="event-map"><Suspense fallback={<p>Unfolding the venue map…</p>}><MapCanvas center={area} places={mapped} onSelect={onSelect} onMove={onMove}/></Suspense></div><p>© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>. Unlocated pilot picks stay in the list.</p></>}
    {!loading && !visible.length && <p>No venues match this area/type yet. Try another area or add a missing venue.</p>}<ul className="calendar-cards">{visible.map(venue => <li key={venue.id}><span className="eyebrow">{venue.source} · {venue.kind}</span><h2>{venue.name}</h2><p>{venue.address}</p><p>{venue.lat !== undefined ? `${distanceKm(area, { lat: venue.lat, lon: venue.lon! }).toFixed(1)} km` : 'Pilot-city pick · distance unknown'}</p><button onClick={() => chooseVenue(venue)}>Venue details ↗</button></li>)}</ul>
    {selected && <aside className="calendar-note" aria-label="Venue details"><button ref={detailClose} onClick={() => setSelected(null)}>Close venue details</button><span className="eyebrow">{selected.source} · {selected.kind}</span><h2>{selected.name}</h2><p>{selected.address}</p><p>Hours: {selected.hours}</p>{selected.kind === 'gaming' && <p>OSM gaming tags may include adult gaming centres or game shops. Confirm activities and age limits with the venue.</p>}{selected.phone && <a href={`tel:${selected.phone}`}>Call venue: {selected.phone}</a>}{selected.lat !== undefined && <a href={googleMapsLink({ lat: selected.lat, lon: selected.lon! }, 'drive')} target="_blank" rel="noreferrer">Directions ↗</a>}<p>Price note: {selected.price_note || 'Price not supplied.'}</p><p>Last updated: {selected.price_updated_at || 'Unknown'}. Confirm on the booking site; price notes are not live quotes.</p><div className="booking-links">{selected.website && <a href={selected.website} target="_blank" rel="noreferrer">Venue’s own site ↗</a>}{cityBookingLinks(area.city).map(link => <a key={link.label} href={link.url} target="_blank" rel="noreferrer">{link.label} ↗</a>)}{selected.booking_links.map(link => <a key={link.url} href={link.url} target="_blank" rel="noreferrer">Other booking: {link.label} ↗</a>)}</div><p>Browse links do not confirm this venue is listed or tickets are available. No official partnership.</p>{selected.sourceUrl && <a href={selected.sourceUrl} target="_blank" rel="noreferrer">Venue data source ↗</a>}{selected.directorySourceUrl && <a href={selected.directorySourceUrl} target="_blank" rel="noreferrer">Pilot directory source ↗</a>}<FavoriteButton key={`favorite:${selected.id}`} place={{ id: selected.id, name: selected.name, category: selected.kind, address: selected.address, hours: selected.hours, lat: selected.lat, lon: selected.lon, sourceUrl: selected.sourceUrl }}/><Suspense fallback={<p role="status">Opening traveller notes…</p>}><Reviews key={`reviews:${selected.id}`} placeId={selected.id}/></Suspense><Crowd key={selected.id} placeId={selected.id}/><details><summary>Report wrong price</summary><form className="event-form" onSubmit={priceReport}><label>What needs correcting?<textarea name="reason" required minLength={10} maxLength={300}/></label><button disabled={busy}>Submit price report</button><p role="status">{reportMessage}</p></form></details></aside>}
    <section aria-label="What's on"><h2>What’s on?</h2><p>Provider city pages, venue sites and SPOTLAND’s community/open-data events, with sources shown.</p><div className="booking-links">{cityBookingLinks(area.city).map(link => <a key={link.label} href={link.url} target="_blank" rel="noreferrer">{link.label} ↗</a>)}</div><button onClick={() => setShowEvents(true)}>Browse community &amp; Wikidata events ↗</button></section>
    <details><summary>Add a missing venue</summary><p>Only public venue details and your own price note. No copied ticket listings, private addresses or contact details.</p><form className="event-form" onSubmit={add}>{[['name','Name'],['city','City'],['address','Public address'],['hours','Hours (optional)'],['phone','Public phone (optional)'],['website','HTTPS venue website (optional)'],['price_note','Price note (optional)'],['booking_label','Other booking provider label (optional)'],['booking_url','Other HTTPS booking link (optional)']].map(([name,label]) => <label key={name}>{label}<input name={name} required={['name','city','address'].includes(name)} maxLength={name.includes('url') || name === 'website' ? 400 : name === 'address' ? 200 : name === 'price_note' ? 160 : name === 'hours' ? 150 : name === 'booking_label' ? 40 : name === 'city' ? 80 : 100}/></label>)}<label>Venue type<select name="kind">{venueKinds.map(value => <option key={value}>{value}</option>)}</select></label><label>Public venue latitude<input name="lat" type="number" min={6} max={38} step="any" required/></label><label>Public venue longitude<input name="lon" type="number" min={68} max={98} step="any" required/></label><button disabled={busy}>Submit venue for review</button><p role="status">{formMessage}</p></form></details>
    <details><summary>Venue moderator access</summary><p>Token stays in memory. Verify links, source rights, hours, phone and price before approval. Correct OSM/seed sources separately; resolving a report does not change its price.</p><label>Moderator token<input type="password" autoComplete="off" value={token} onChange={event => { setToken(event.target.value); tokenRef.current = event.target.value; setPending([]); setReports([]); setAdminMessage(''); }}/></label><button disabled={!token || busy} onClick={() => void loadAdmin()}>Load pending venues &amp; reports</button><p role="status">{adminMessage}</p>{pending.map(venue => <div key={venue.id}><h3>{venue.name}</h3><pre className="venue-review">{JSON.stringify(venue,null,2)}</pre><button disabled={busy} onClick={() => void moderate(venue.id,'approved')}>Approve {venue.name}</button><button disabled={busy} onClick={() => void moderate(venue.id,'rejected')}>Reject {venue.name}</button></div>)}{reports.map(report => <div key={report.id}><p>{report.venue_id}: {report.reason}</p><button disabled={busy} onClick={() => void moderate(report.id,'resolved')}>Resolve report</button></div>)}</details>
  </div></section>;
}



